CREATE DATABASE OOP;
USE OOP;
CREATE TABLE oop_info(oop_date DATE NOT NULL, PRIMARY KEY(oop_date));
SHOW columns from oop_info;
INSERT INTO oop_info(oop_date) VALUES ('1998-09-05');
INSERT INTO oop_info(oop_date) VALUES ('1999-12-31');
INSERT INTO oop_info(oop_date) VALUES ('2000-02-31');
select * from oop_info;
select adddate('1927-03-16', interval 3 day);
DROP DATABASE OOP;