CREATE DATABASE ldhuhp;
CREATE DATABASE dzj;
CREATE DATABASE vghyv;
USE ldhuhp;
CREATE TABLE ldhuhp(ppbkoqnvgm INT, gregdodxcv INT, keszrwtlfu INT, lqhnzjnnnbz INT NOT NULL, PRIMARY KEY(lqhnzjnnnbz));
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (188, NULL, 154, 3);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (173, 147, NULL, 10);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (192, 158, 165, 7);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (159, 182, NULL, 8);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (138, 161, NULL, 5);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (151, 149, 171, 2);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (NULL, NULL, 180, 4);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (183, 194, 194, 6);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (160, 185, NULL, 9);
INSERT INTO ldhuhp(ppbkoqnvgm, gregdodxcv, keszrwtlfu, lqhnzjnnnbz) VALUES (NULL, 152, 131, 1);
SELECT COUNT(ppbkoqnvgm) from ldhuhp;
SELECT COUNT(gregdodxcv) from ldhuhp;
SELECT COUNT(lqhnzjnnnbz) from ldhuhp;
SELECT COUNT(gregdodxcv) from ldhuhp;
DROP DATABASE ldhuhp;
DROP DATABASE dzj;
DROP DATABASE vghyv;
